a={"anagha",22,"rejoice","vismaya",23}
print(a)
print(type(a))
print(len(a))
y=set((10,20,30,40,50))
print(y)
for i in a:
    print(i)
print(10 in y)
print(10 not in y)
y.add(2255)
print(y)
a.update(y)
print(a)
colour=("red","blue","green")
print(colour)
a.update(colour)
print(a)
a.remove(2255)
print(a)
a.discard("apple")
print(a)
a.discard(10)
print(a)
b=a.pop()
print(b)
a.pop()
print(a)
# y.clear()
# print(y)
# del a
d=a.union(y)
print(d)
ab={"apple",10,20,"greenapple","mango"}
bc={"man",10,"apple","mangochilli",20}
de=ab.intersection(bc)
print(de)
bo=ab.difference(bc)
print(bo)
ty=bc.difference(ab)
print(ty)