a={"priya",22j,"motorcycle","manoj",23}
print(a)
print(type(a))
print(len(a))
y=set((1,3,5,7,9))
print(y)
for i in a:
    print(i)
print(5 in y)
print(5 not in y)
y.add(4545)
print(y)
a.update(y)
print(a)
teams=("red","blue","green")
print(teams)
a.update(teams)
print(a)
a.remove(4545)
print(a)
a.discard("priya")
print(a)
a.discard(5)
print(a)
b=a.pop()
print(b)
a.pop()
print(a)
d=a.union(y)
print(d)
ab={"apple",11,44,"greenapple","mango"}
bc={"man",11,"apple","chilliapple",20}
de=ab.intersection(bc)
print(de)
bo=ab.difference(bc)
print(bo)
ty=bc.difference(ab)
print(ty)